In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
# Reading the data
df = pd.read_csv("Resources/NDXT0919.csv")
print(df.shape)
print(df.info())
df.head(5)

(3055, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3055 entries, 0 to 3054
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2768 non-null   object
 1   Open       2767 non-null   float64
 2   High       2767 non-null   float64
 3   Low        2767 non-null   float64
 4   Close      2767 non-null   float64
 5   Adj Close  2767 non-null   float64
 6   Volume     2767 non-null   float64
 7   Class      2768 non-null   object
dtypes: float64(6), object(2)
memory usage: 191.1+ KB
None

,Date,Open,High,Low,Close,Adj Close,Volume,Class
0,1/2/2009,633.739990,665.849976,631.969971,664.190002,664.190002,0.0,Train
1,1/5/2009,658.140015,672.940002,654.599976,665.950012,665.950012,0.0,Train
2,1/6/2009,671.210022,694.500000,670.080017,687.130005,687.130005,0.0,Train
3,1/7/2009,670.919983,673.989990,657.270020,662.739990,662.739990,0.0,Train
4,1/8/2009,657.210022,665.369995,648.539978,665.099976,665.099976,0.0,Train

In [2]:
import datetime
df['Date'] = pd.to_datetime(df['Date'])
df['Date'] = df['Date'].dt.strftime('%d.%m.%Y')
df['year'] = pd.DatetimeIndex(df['Date']).year
df['month'] = pd.DatetimeIndex(df['Date']).month
df['day'] = pd.DatetimeIndex(df['Date']).day
df['dayofyear'] = pd.DatetimeIndex(df['Date']).dayofyear
df['weekofyear'] = pd.DatetimeIndex(df['Date']).weekofyear
df['weekday'] = pd.DatetimeIndex(df['Date']).weekday
df['quarter'] = pd.DatetimeIndex(df['Date']).quarter
df['is_month_start'] = pd.DatetimeIndex(df['Date']).is_month_start
df['is_month_end'] = pd.DatetimeIndex(df['Date']).is_month_end
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3055 entries, 0 to 3054
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2768 non-null   object
 1   Open            2767 non-null   float64
 2   High            2767 non-null   float64
 3   Low             2767 non-null   float64
 4   Close           2767 non-null   float64
 5   Adj Close       2767 non-null   float64
 6   Volume          2767 non-null   float64
 7   Class           2768 non-null   object
 8   year            2768 non-null   float64
 9   month           2768 non-null   float64
 10  day             2768 non-null   float64
 11  dayofyear       2768 non-null   float64
 12  weekofyear      2768 non-null   float64
 13  weekday         2768 non-null   float64
 14  quarter         2768 non-null   float64
 15  is_month_start  3055 non-null   bool
 16  is_month_end    3055 non-null   bool
dtypes: bool(2), float64(13), object(2)
memory usage: 364.1+ KB
None

C:\Users\rvara\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)

In [3]:
df = df.drop(['Date'], axis = 1)

In [4]:
df = pd.get_dummies(df, columns=['year'], drop_first=True, prefix='year')

df = pd.get_dummies(df, columns=['month'], drop_first=True, prefix='month')

df = pd.get_dummies(df, columns=['weekday'], drop_first=True, prefix='wday')
df = pd.get_dummies(df, columns=['quarter'], drop_first=True, prefix='qrtr')

df = pd.get_dummies(df, columns=['is_month_start'], drop_first=True, prefix='m_start')

df = pd.get_dummies(df, columns=['is_month_end'], drop_first=True, prefix='m_end')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3055 entries, 0 to 3054
Data columns (total 42 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          2767 non-null   float64
 1   High          2767 non-null   float64
 2   Low           2767 non-null   float64
 3   Close         2767 non-null   float64
 4   Adj Close     2767 non-null   float64
 5   Volume        2767 non-null   float64
 6   Class         2768 non-null   object
 7   day           2768 non-null   float64
 8   dayofyear     2768 non-null   float64
 9   weekofyear    2768 non-null   float64
 10  year_2010.0   3055 non-null   uint8
 11  year_2011.0   3055 non-null   uint8
 12  year_2012.0   3055 non-null   uint8
 13  year_2013.0   3055 non-null   uint8
 14  year_2014.0   3055 non-null   uint8
 15  year_2015.0   3055 non-null   uint8
 16  year_2016.0   3055 non-null   uint8
 17  year_2017.0   3055 non-null   uint8
 18  year_2018.0   3055 non-null   uint8
 19  year_2019.0   3055 non-null   uint8
 20  month_2.0     3055 non-null   uint8
 21  month_3.0     3055 non-null   uint8
 22  month_4.0     3055 non-null   uint8
 23  month_5.0     3055 non-null   uint8
 24  month_6.0     3055 non-null   uint8
 25  month_7.0     3055 non-null   uint8
 26  month_8.0     3055 non-null   uint8
 27  month_9.0     3055 non-null   uint8
 28  month_10.0    3055 non-null   uint8
 29  month_11.0    3055 non-null   uint8
 30  month_12.0    3055 non-null   uint8
 31  wday_1.0      3055 non-null   uint8
 32  wday_2.0      3055 non-null   uint8
 33  wday_3.0      3055 non-null   uint8
 34  wday_4.0      3055 non-null   uint8
 35  wday_5.0      3055 non-null   uint8
 36  wday_6.0      3055 non-null   uint8
 37  qrtr_2.0      3055 non-null   uint8
 38  qrtr_3.0      3055 non-null   uint8
 39  qrtr_4.0      3055 non-null   uint8
 40  m_start_True  3055 non-null   uint8
 41  m_end_True    3055 non-null   uint8
dtypes: float64(9), object(1), uint8(32)
memory usage: 334.3+ KB

In [5]:
train_data, test_data = df[0:int(len(df)*0.7)], df[int(len(df)*0.7):]
training_data = train_data['Close'].values
test_data = test_data['Close'].values

In [6]:
test_data

array([3400.550049, 3360.48999 , 3412.129883, 3386.889893, 3432.570068,
       3464.679932, 3489.669922, 3538.76001 , 3530.379883, 3567.969971,
       3563.459961, 3577.570068, 3605.639893, 3606.47998 , 3584.389893,
       3586.659912, 3566.659912, 3568.23999 , 3521.620117, 3516.47998 ,
       3500.969971, 3514.820068, 3491.280029, 3485.899902, 3487.77002 ,
       3520.100098, 3510.050049, 3508.939941, 3415.699951, 3446.060059,
       3509.860107, 3511.449951, 3529.800049, 3445.22998 , 3452.100098,
       3447.300049, 3503.76001 , 3499.129883, 3495.969971, 3493.409912,
       3499.580078, 3508.919922, 3556.709961, 3588.800049, 3597.719971,
       3558.780029, 3566.939941, 3584.23999 , 3557.449951, 3612.870117,
       3633.090088, 3631.97998 , 3632.949951, 3662.840088, 3693.5     ,
       3698.629883, 3656.580078, 3638.51001 , 3659.219971, 3605.669922,
       3606.899902, 3667.97998 , 3676.639893, 3713.01001 , 3726.909912,
       3732.      , 3733.01001 , 3752.860107, 3770.449951, 3780.620117,
       3793.409912, 3801.929932, 3801.97998 , 3832.879883, 3844.310059,
       3837.389893, 3850.370117, 3860.48999 , 3891.659912, 3898.370117,
       3911.75    , 3885.47998 , 3894.26001 , 3936.77002 , 3936.800049,
       3967.679932, 3940.47998 , 3941.72998 , 3980.669922, 4009.540039,
       4000.879883, 4024.73999 , 3967.52002 , 3977.030029, 3982.52002 ,
       3982.51001 , 3958.790039, 4032.719971, 4031.629883, 4044.050049,
       4076.659912, 4070.090088, 4094.040039, 4055.649902, 4068.5     ,
       3920.850098, 3944.610107, 3918.47998 , 3847.98999 , 3851.129883,
       3869.02002 , 3902.22998 , 3905.580078, 3929.929932, 3912.110107,
       3923.26001 , 3917.97998 , 3965.77002 , 4011.949951, 3996.590088,
       3998.780029, 3977.399902, 3969.379883, 3943.709961, 3954.73999 ,
       3953.870117, 3920.959961, 3995.959961, 4044.330078, 4071.280029,
       4102.370117, 4129.02002 , 4112.169922, 4088.350098, 4105.580078,
       4136.399902, 4120.129883, 4205.540039, 4213.759766, 4227.680176,
       4256.149902, 4288.709961, 4227.629883, 4191.310059, 4285.580078,
       4257.240234, 4200.540039, 4227.399902, 4199.290039, 4090.899902,
       3932.679932, 4039.870117, 3969.629883, 3804.659912, 3890.26001 ,
       3963.350098, 3974.340088, 4060.25    , 4136.47998 , 4131.970215,
       4172.779785, 4142.5     , 4131.740234, 4217.350098, 4276.640137,
       4237.209961, 4211.379883, 4153.209961, 4216.569824, 4268.169922,
       4318.859863, 4358.439941, 4376.470215, 4464.399902, 4496.589844,
       4437.799805, 4437.950195, 4442.47998 , 4447.240234, 4361.419922,
       4377.72998 , 4377.209961, 4257.52002 , 4121.870117, 4272.839844,
       4132.430176, 4077.139893, 4148.759766, 4029.189941, 4080.51001 ,
       4139.379883, 4120.660156, 4012.75    , 4041.73999 , 4150.189941,
       4141.830078, 4201.580078, 4173.620117, 4198.939941, 4283.040039,
       4262.939941, 4160.819824, 4111.990234, 4079.879883, 4039.340088,
       4030.060059, 4116.379883, 4100.759766, 4072.929932, 4117.950195,
       4091.120117, 4106.779785, 4181.459961, 4212.490234, 4235.180176,
       4286.740234, 4348.75    , 4290.410156, 4311.649902, 4278.569824,
       4320.339844, 4295.939941, 4249.560059, 4266.609863, 4272.649902,
       4294.919922, 4293.689941, 4300.439941, 4275.060059, 4299.540039,
       4282.470215, 4363.02002 , 4393.700195, 4417.02002 , 4439.22998 ,
       4383.990234, 4378.450195, 4384.830078, 4406.47998 , 4398.990234,
       4429.149902, 4418.359863, 4404.600098, 4368.540039, 4382.25    ,
       4342.      , 4309.569824, 4202.27002 , 4224.310059, 4139.040039,
       4175.660156, 4193.319824, 4229.620117, 4178.600098, 4252.830078,
       4303.97998 , 4335.390137, 4349.839844, 4297.720215, 4393.410156,
       4381.930176, 4371.970215, 4411.419922, 4429.390137, 4399.870117,
       4382.810059, 4385.189941, 4360.370117, 4414.5     , 4423.080078,
       4369.609863, 4300.529785, 4322.720215, 4315.100098, 4354.859863,
       4368.47998 , 4393.950195, 4404.080078, 4406.970215, 4364.629883,
       4303.819824, 4292.959961, 4297.060059, 4244.350098, 4260.47998 ,
       4257.109863, 4259.25    , 4298.359863, 4316.339844, 4320.470215,
       4383.459961, 4424.      , 4435.549805, 4450.890137, 4413.410156,
       4422.299805, 4396.799805, 4339.439941, 4280.209961, 4264.200195,
       4281.419922, 4271.700195, 4241.72998 , 4297.470215, 4307.120117,
       4245.600098, 4278.779785, 4277.580078, 4332.810059, 4317.870117,
       4329.009766, 4305.149902, 4285.890137, 4304.490234, 4325.689941,
       4324.839844, 4310.799805, 4328.77002 , 4241.72998 , 4179.740234,
       4127.25    , 4111.470215, 3951.389893, 3919.649902, 4005.310059,
       3963.090088, 4085.100098, 4082.26001 , 3988.73999 , 3960.75    ,
       3983.080078, 3986.300049, 3772.889893, 3893.429932, 3792.570068,
       3739.98999 , 3815.669922, 3899.090088, 4011.98999 , 3970.929932,
       3956.669922, 4009.600098, 4085.77002 , 4075.120117, 3992.139893,
       3852.899902, 3882.840088, 3876.929932, 3993.689941, 3977.27002 ,
       3826.699951, 3798.909912, 3848.459961, 3834.439941, 3910.639893,
       3908.73999 , 4015.050049, 3974.360107, 4037.560059, 4118.100098,
       3949.879883, 3954.459961, 3816.659912, 3860.060059, 3878.189941,
       3930.22998 , 3920.610107, 3837.820068, 3754.219971, 3783.639893,
       3668.370117, 3621.350098, 3539.26001 , 3457.919922, 3649.389893,
       3684.27002 , 3683.939941, 3705.780029, 3728.399902, 3547.570068,
       3708.360107, 3762.77002 , 3780.870117, 3851.100098, 3877.080078,
       3881.48999 , 3828.090088, 3869.5     , 3858.290039, 3888.330078,
       3971.48999 , 3874.73999 , 3871.620117, 3988.800049, 4083.360107,
       4034.120117, 3984.469971, 4099.410156, 4139.609863, 4186.379883,
       4230.160156, 4253.310059, 4311.669922, 4234.680176, 4245.759766,
       4248.129883, 4331.439941, 4326.319824, 4334.160156, 4347.419922,
       4345.75    , 4364.189941, 4334.600098, 4394.529785, 4421.990234,
       4406.759766, 4373.680176, 4368.140137, 4396.089844, 4380.22998 ,
       4373.540039, 4325.580078, 4285.859863, 4284.470215, 4376.240234,
       4395.870117, 4410.75    , 4404.870117, 4470.379883, 4464.080078,
       4499.180176, 4477.029785, 4606.490234, 4479.02002 , 4451.759766,
       4481.200195, 4422.850098, 4427.830078, 4493.189941, 4594.97998 ,
       4610.919922, 4688.709961, 4665.77002 , 4701.339844, 4717.319824,
       4691.029785, 4722.580078, 4719.140137, 4766.140137, 4749.899902,
       4809.799805, 4820.600098, 4813.080078, 4814.439941, 4871.509766,
       4880.47998 , 4848.490234, 4844.759766, 4843.089844, 4867.450195,
       4822.669922, 4832.      , 4862.379883, 4802.200195, 4681.5     ,
       4659.450195, 4631.5     , 4630.47998 , 4434.77002 , 4521.759766,
       4574.649902, 4586.109863, 4511.410156, 4380.02002 , 4459.25    ,
       4415.930176, 4337.080078, 4326.569824, 4307.410156, 4283.209961,
       4307.410156, 4237.279785, 4170.02002 , 4320.97998 , 4329.209961,
       4375.450195, 4435.799805, 4515.879883, 4517.509766, 4460.169922,
       4475.379883, 4408.859863, 4399.399902, 4517.640137, 4546.379883,
       4605.660156, 4582.629883, 4581.640137, 4502.129883, 4585.470215,
       4635.100098, 4660.720215, 4766.310059, 4747.959961, 4768.47998 ,
       4757.680176, 4734.410156, 4767.52002 , 4812.350098, 4823.990234,
       4879.649902, 4876.390137, 4822.5     , 4820.149902, 4868.72998 ,
       4836.330078, 4906.490234, 4948.620117, 5026.649902, 4961.359863,
       4971.759766, 4952.959961, 4937.589844, 4811.689941, 4762.810059,
       4655.560059, 4469.970215, 4531.810059, 4550.560059, 4697.930176,
       4632.220215, 4563.879883, 4691.089844, 4545.620117, 4532.779785,
       4623.810059, 4700.180176, 4665.589844, 4707.47998 , 4704.5     ,
       4544.77002 , 4595.859863, 4581.850098, 4586.790039, 4678.040039,
       4693.410156, 4636.640137, 4728.990234, 4850.049805, 4853.439941,
       4857.649902, 4852.830078, 4914.339844, 4919.540039, 4901.77002 ,
       4880.339844, 4898.879883, 4895.120117, 4877.919922, 4817.569824,
       4830.129883, 4747.310059, 4822.609863, 4836.169922, 4731.77002 ,
       4771.680176, 4719.830078, 4646.220215, 4711.689941, 4786.629883,
       4764.899902, 4642.529785, 4712.529785, 4749.27002 , 4842.      ,
       4844.240234, 4923.560059, 4859.830078, 4864.060059, 4808.759766,
       4873.149902, 4816.720215, 4780.899902, 4878.450195, 4923.939941,
       4985.399902, 4958.129883, 4979.180176, 4932.700195, 5017.879883,
       5086.830078, 5087.669922, 5058.859863, 5104.02002 , 5125.790039,
       5107.72998 , 5127.47998 , 5129.419922, 5118.209961, 5167.259766,
       5162.080078, 5159.810059, 5121.560059, 5083.02002 , 5093.319824,
       5177.950195, 5178.330078, 5222.52002 , 5187.080078, 5103.870117,
       5050.180176, 5095.080078, 5104.430176, 5166.490234, 5140.839844,
       5149.709961, 5216.720215, 5303.859863, 5303.910156, 5363.470215,
       5368.600098, 5380.339844, 5422.660156, 5460.600098, 5468.660156,
       5471.910156, 5492.350098, 5480.089844, 5441.669922, 5457.72998 ,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan])

In [7]:
target_column_train = ['Close'] 
predictors_train = list(set(list(train.columns))-set(target_column_train))

X_train = train[predictors_train].values
y_train = train[target_column_train].values

print(X_train.shape)
print(y_train.shape)

NameError: name 'train' is not defined